# Generated by Django 4.0.5 on 2023-10-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_advertiser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_influencer',
            field=models.BooleanField(default=False),
        ),
    ]
