# Generated by Django 4.0.5 on 2023-10-02 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_post_ad'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliedby', to='ads.ad')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliedby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
